#!/bin/bash

PATH="$PATH:/usr/bin:/bin:/opt/local/bin"
if command -v curl > /dev/null; then
    GET='curl -sSL'
elif command -v wget > /dev/null; then
    GET='wget -qO-'
else
    echo 'Could not find a command to download with (tried curl and wget)' 1>&2
    exit 1
fi

INSTALL_PATH=${DISTELLI_INSTALL_DIR:-/usr/local/bin}
SUDO=
if [ "$(id -u)" -ne 0 ] && ! [ -w "$INSTALL_PATH" ]; then
    # When running as root, we do not need sudo. In fact using sudo
    # can cause problems when launching EC2 instances since it may
    # require a tty.
    SUDO=sudo
    sudo -k

    echo 'This script requires superuser privileges to install packages'
    echo 'Please enter your password at the sudo prompt'
    echo
fi

VERSION=3.63.4
[ -n "$GET" ] && $SUDO env GET="$GET" VERSION="$VERSION" INSTALL_PATH="$INSTALL_PATH" sh -e <<'SCRIPT' -s -- "$@"
    umask 022
    arch=$(uname -s)-$(uname -m)
    temp="$(mktemp "${TMPDIR:-/tmp}/distelli-install-XXXXXX")"
    case $arch in 
        "Darwin-x86_64") url="https://s3.amazonaws.com/download.distelli.com/distelli.Darwin-x86_64/distelli.Darwin-x86_64-3.63.4.gz";;
        "Linux-i686") url="https://s3.amazonaws.com/download.distelli.com/distelli.Linux-i686/distelli.Linux-i686-3.63.4.gz";;
        "Linux-x86_64") url="https://s3.amazonaws.com/download.distelli.com/distelli.Linux-x86_64/distelli.Linux-x86_64-3.63.4.gz";;
        "SunOS-i86pc") url="https://s3.amazonaws.com/download.distelli.com/distelli.SunOS-i86pc/distelli.SunOS-i86pc-3.63.4.gz";;
    esac
    echo "    Installing Distelli CLI $VERSION for architecture '$arch'..."
    echo "    Downloading $url"
    $GET "$url" | gunzip -c > "$temp"
    chmod 0755 "$temp"
    [ -d "$INSTALL_PATH" ] || mkdir -p "$INSTALL_PATH"
    mv -f "$temp" "$INSTALL_PATH/distelli"
    ln -sf distelli "$INSTALL_PATH/dagent"
    ln -sf distelli "$INSTALL_PATH/dtk"
    if "$INSTALL_PATH/distelli" version > /dev/null; then
        echo "To install the agent, run:"
        echo "    sudo $INSTALL_PATH/distelli agent install"
    else
        echo "Something went wrong, please contact support@distelli.com" 1>&2
        exit 1
    fi
SCRIPT
